### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by anton-matsyshyn** [MatsyshynAnton/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by 0lyaMelnyk** [comment]
<div class="sixteen wide column">
                                  <h2>Резюме</h2>
                                  <p>&mdash; Ви думали, що це звичайне резюме?! Але це я, Діо! Я головний антагоніст
                                                        саги JoJo's Bizarre Adventure, до того ж вампір і маю крутий станд 
                                                        &#763;<small> <a href="https://jojo.fandom.com/ru/wiki/The_World" rel="external">T H E W O R L D</a></small>&#762; !
                                                        Я відмінний маніпулятор і стратег, і моя головна ціль &#8211; знищити сімейство клятих Джостарів
                                                        (на жаль, минулі дві спроби не були достатньо успішними). Якщо вам треба когось анігілювати &#8211; 
                                                        ви знаєте до кого звернутися.
                                    </p>
                                  <p style="opacity: 0.75;">
                                    Is that a <a href="https://www.quora.com/Why-is-everything-a-Jojo-reference"
                                                        rel="external">JoJo reference</a>?!
                                  </p>
                                </div>

**Comment by anton-matsyshyn** [comment]
@0lyaMelnyk , пасибі ^^
