### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by anton-matsyshyn** [MatsyshynAnton/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by 0lyaMelnyk** [comment]
<h6>Трохи раніше...</h6>
                          <ul class="timeline">
                                              <li>
                                                  <p><em>1988</em></p>
                                                  <p>
                                                      Не було такого ніколи і ось знову! Я 
                                                      <strong>переможений черговим <a href="https://jojo.fandom.com/ru/wiki/%D0%94%D0%B6%D0%BE%D1%82%D0%B0%D1%80%D0%BE_%D0%9A%D1%83%D0%B4%D0%B6%D0%BE">
                                                      ДжоДжо</a></strong>... Цьому хлопчиську всього сімнадцять, а він зумів подолати мене, 
                                                      величного і страшного Діо. Схоже, я десь звернув не туди 😩.
                                                  </p>
                                              </li>
                            <li>
                              <p><em>1987</em></p>
                              <p>
                                                      У мене <strong>народився <a href="https://www.youtube.com/watch?v=2MtOpB5LlUA&t=3m45s">
                                                      син</a></strong> 👶! Через шістнадцять років він переможе боса 
                                                      італійської мафії, але тільки заради того, щоб зайняти його місце 😡.
                              </p>
                            </li>
                            <li>
                              <p><em>1987</em></p>
                              <p>
                                                      З новою силою можна <strong>потягатись і з новим поколінням Джостарів</strong>! 
                                                      Ну, цього разу точно переможу!
                                                  </p>
                            </li>
                            <li>
                              <p><em>1986</em></p>
                              <p>
                                                      Пум-пум ту-ту-ту я <strong>отримав станд</strong>! 
                                                      Для тих хто не в темі <strong>станд &#8211; це суперздібність</strong>, 
                                                      що втілює собою волю свого володара. Моя воля міцна як сталь, тож станд я 
                                                      отримав настільки ж сильний.
                                                  </p>
                            </li>
                            <li>
                              <p><em>1985</em></p>
                              <p>
                                                      Хо-хо-хо! Доля накінець посміхнулася мені! З дна океану мене випадково підняли 
                                                      якісь шукачі скарбів. Ну, мені, звичайно, приємно, що навіть через сто років 
                                                      мене цінять настільки сильно 😂, але це не врятувало бідолаг від моєї жаги крові. 
                                                      Тим паче, останні промені сонця тоді якраз опускалися за горизонт...
                                                  </p>
                            </li>
                            <li>
                                                  <p><em>1879 - 1985</em></p>
                                                  <p>
                                                      Лежу на дні <strong>Атлантичного океану</strong> та рахую баранців.
                                                  </p>
                            </li>
                            <li>
                              <p><em>1879</em></p>
                              <ul>
                                <li class="details">
                                  <input type="checkbox" id="fight">
                                  <label for="fight" class="summary">Тут буде <strong>довгий опис</strong> наших з Джонатаном <strong>махачів</strong>. 
                                                              Для нетепрлячих скажу відверто і коротко: я недооцінив цього недоумка, через що пролежав
                                                              більше ста років на морському дні. Хоча і отримав вампірські здібності.
                                  </label>
                                  <div>
                                    <ul>
                                      <li>перша битва сталася у маєтку, де він превсилюдно розкрив мої інтриги. 
                                                                      Коли я зрозумів, що програв, я одягнув кам'яну маску та перетворився на вампіра. 
                                                                      Спалив дотла маєток, але так і не зміг перемогти Джонатана (ну він же протагоніст, що ви хотіли).
                                                                  </li>
                                      <li>
                                                                      наступного разу ми зустрілися на моїй території. Я створив цілу армію нежиті, 
                                                                      але мій супротивник також не зволікав і освої якесь дивне <a rel="external" href="https://jojo.fandom.com/ru/wiki/%D0%A5%D0%B0%D0%BC%D0%BE%D0%BD">
                                                                      сонячне карате</a> зі смішною назвою. 
                                                                      Доречі, сонце, як і будь-який вампір я не дуже полюбляю. Закінчилося це все моєю повною поразкою 😢.
                                                                  </li>
                                      <li>
                                                                      наш останній бій відбувся на кораблі, на якому Джонатан зі своєю дружиною відпливав у 
                                                                      медовий місяць. У мене накінець вийшло перемогти його, але він заточив мене на морському дні 
                                                                      більше як на сто років! :( До того ж, зумів врятувати свою дружину. Що тут скажеш &#8211; 
                                                                      типічний головний герой.
                                      </li>
                                    </ul>
                                  </div>
                                </li>
                              </ul>
                                              </li>
                                              <li>
                                                  <p><em>1879</em></p>
                                                  <p>
                                                      Відкриваю секрет <strong>кам'яної маски</strong>.
                                                      Якщо надягнути її на людину, то вона перетворить носія
                                                      на вампіра! Тепер мене ніщо не зупинть!
                                                  </p>
                                              </li>
                            <li>
                              <p><em>1879</em></p>
                                                  <p><strong>Нарешті готовий! </strong> 
                                                      Підмішую отурту у вино Джорджа, але Джонатан починає щось підозрювати...
                                                  </p>
                            </li>
                            <li>
                                                  <p><em>1878</em></p>
                                                  <p>Планую усунути голову сім'ї за допомогою отрути (і всю вину перекласти на Джонатана). 
                                                      Кажуть, що це зброя боягузів, але заради спадку я піду на все.
                                                  </p></li>
                            <li>
                              <p><em>1870 &ndash; 1878</em></p>
                              <ul>
                                <li class="details">
                                  <input type="checkbox" id="goldfish">
                                  <label for="goldfish" class="summary">
                                    <strong>Живу і процвітаю</strong> як <strong>справжній аристократ</strong>
                                  </label>
                                  <div>
                                    <ul>
                                      <li>
                                                                      відмінно навчаюсь у коледжі
                                                                  </li>
                                      <li>
                                                                      стаю хлопцем "на масі"
                                                                  </li>
                                      <li>
                                                                      намагаюсь втертися в довіру до Джонатана 
                                                                      щоб він не заважав мені плести інтриги проти їх сімейства
                                                                  </li>
                                    </ul>
                                  </div>
                                </li>
                              </ul>
                                              </li>
                            <li>
                                                  <p><em>1871</em></p>
                                                  <ul>
                                                      <li class="details">
                                                          <input type="checkbox" id="inheritor">
                                                          <label for="inheritor" class="summary">
                                                              <strong>Перетворюю життя</strong> спадкоємця <strong>на пекло</strong>
                                                          </label>
                                                          <div>
                                                              <ul>
                                                                  <li>
                                                                      відбиваю у нього гарненьку дівчину 
                                                                      (якщо начистоту, у Джонатана все одно ніяких шансів).
                                                                  </li>
                                                                  <li>
                                                                      виставляю його йолопом перед усім містом, тож навряд чи він 
                                                                      тепер знайде собі друзів.
                                                                  </li>
                                                              </ul>
                                                          </div>
                                                      </li>
                                                  </ul>
                                              </li>
                                              <li>
                              <p><em>1870</em></p>
                              <ul>
                                <li class="details">
                                  <input type="checkbox" id="estate">
                                  <label for="estate" class="summary">
                                    <strong>Вриваюся в маєток Джостарів</strong> наче грім серед ясного неба!
                                  </label>
                                  <div>
                                    <ul>
                                      <li>Першого ж дня показую свій характер та сварюся
                                                                      з Джонатаном Джостаром &#8211; молодим спадкоємцем 
                                                                      цієї багатої сім'ї. Тепер він знає, що я не простолюдин з вулиці.
                                                                  </li>
                                      <li>
                                                                      Виставляю себе у найліпшому вигляді перед головою сім'ї,
                                                                      Джорджом Джостаром, чим з першого ж дня завойовую його довіру.
                                                                  </li>
                                    </ul>
                                  </div>
                                </li>
                              </ul>
                            </li>
                            <li>
                              <p><em>1868</em></p>
                              <p>
                                                      Випадково мій батько <strong>рятує сім'ю багатих аристократів</strong>, Джостарів, тож як тільки я 
                                                      увійду у свідомий вік, для мене відкриються двері їх сімейного маєтку.
                                                  </p>
                            </li>
                            <li>
                              <p><em>1867</em></p>
                                                  <p><strong>Народився</strong> у <strong>Великій Британії</strong>,
                                                      в бідній і нещасливій сім'ї. Але я з дитинства знав, що багато чого досягну у житті.
                              </p>
                            </li>
                          </ul>
